name: "p4c-lint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  p4c-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: apply-linters
        max-size: 1000M

    # - name: Check submodule ref points.
    #   run: |
    #     ./tools/check-git-submodules.sh

    - name: Build
      run: |
        docker build -t p4c --build-arg IMAGE_TYPE=test --build-arg CMAKE_ONLY=ON .

    - name: Run cpplint.
      run: |
        docker run p4c make cpplint -C build

    - name: Run clang-format.
      run: |
        docker run p4c make clang-format -C build
