name: "p4c-lint"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  p4c-lint:
    runs-on: ubuntu-20.04
    env:
      IMAGE_TYPE: test
      CMAKE_ONLY: ON
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: apply-linters
        max-size: 1000M

    # TODO: This check is disabled because git on the Github serves behaves differently. Unclear why.
    # - name: Check submodule ref points.
    #   run: |
    #     ./tools/check-git-submodules.sh

      - name: Build (Ubuntu 20.04)
        run: |
          sudo cp -rf . /p4c/
          (cd /p4c/ && sudo -E tools/ci-build.sh)
          sudo cp -rf /p4c/.ccache .

    - name: Run cpplint.
      run: make cpplint -C build
      working-directory: /p4c

    - name: Run clang-format.
      run: make clang-format -C build
      working-directory: /p4c
