name: "test-tools"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel any preceding run on the pull request.
concurrency:
  group: tools-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  # Build and test p4tools on Ubuntu 20.04.
  build-and-test-tools:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    env:
      CTEST_PARALLEL_LEVEL: 4
      IMAGE_TYPE: test
      ENABLE_UNIFIED_COMPILATION: ON
      ENABLE_TEST_TOOLS: ON
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: test-tools-${{ matrix.unified }}-${{ runner.os }}
        max-size: 1000M

    - name: Build (Ubuntu 20.04)
      run: |
        tools/ci-build.sh

    - name: Run tests (Ubuntu 20.04)
      # Need to use sudo for the eBPF kernel tests.
      run: sudo -E ctest -R testgen- --output-on-failure --schedule-random
      working-directory: ./build
