name: "test-p4tc-ubuntu"

on:
  schedule:
    # Every day on midnight UTC
    - cron: "0 0 * * *"
  pull_request:
    branches: [main]
  push:
    branches: [main]

# Cancel any preceding run on the pull request.
concurrency:
  group: test-ubuntu-p4tc-stf-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  # Run p4tc stf tests
  test-ubuntu-p4tc-stf:
    # Only run on pull requests with the "p4tc" label.
    if: ${{ github.event_name == 'schedule' || contains(github.event.pull_request.labels.*.name, 'p4tc') }}
    runs-on: ubuntu-24.04
    env:
      CTEST_PARALLEL_LEVEL: 4
      IMAGE_TYPE: test
      BUILD_GENERATOR: Ninja
      INSTALL_STF_P4TC_DEPENDENCIES: ON
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: test-${{ runner.os }}-gcc
          max-size: 1000M

      - name: Build (Ubuntu 24.04, GCC)
        run: |
          tools/ci-build.sh

      - name: Run tests (Ubuntu 24.04)
        # Need to use sudo for the eBPF kernel tests.
        run: sudo -E env PATH="$PATH" uv run ctest --output-on-failure --schedule-random -R "p4tc_samples_stf|p4tc_cleanup|p4tc_setup"
        working-directory: ./build
